PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbo: <http://dbpedia.org/ontology/> 
PREFIX dbp: <http://dbpedia.org/property/> 
PREFIX dbr: <http://dbpedia.org/resource/> 
PREFIX yago: <http://dbpedia.org/class/yago/> 
PREFIX db: <http://www.semanticweb.org/ontologies/databases/tbox/> 




SELECT ?db ?label ?license ?abstract ?progrLang
WHERE { 
  ?db rdf:type db:RelationalDBMS . 
  ?db rdfs:label ?label .
  ?db db:hasLicense ?license .
  { OPTIONAL {?db dbo:programminLanguage ?progrLang. } }
  { OPTIONAL { ?db dbo:abstract ?abstract .} }
  
  FILTER (lang(?label) = 'en') .
  FILTER (lang(?abstract) = 'en') .
}	
