PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbo: <http://dbpedia.org/ontology/> 
PREFIX dbp: <http://dbpedia.org/property/> 
PREFIX dbr: <http://dbpedia.org/resource/> 
PREFIX db: <http://www.semanticweb.org/ontologies/databases/> 


SELECT ?subject ?predicate ?object 
	WHERE { ?subject ?predicate ?object . }
	
	
SELECT ?db 
	WHERE { ?db db:hasDataModel db:KeyValueDataModel . }
	
SELECT ?db 
	WHERE { ?db a db:SoftwareApplication . }
	
SELECT ?db 
	WHERE { ?db rdfs:subClassOf db:DatabaseManagementSystem . }	
	
SELECT ?db 
	WHERE { ?db a db:DatabaseManagementSystem . }	
	
SELECT ?db 
	WHERE { ?db db:isSuitableForSoftwareApplication db:LowLatencySoftwareApplication . }	